language: node_js
os:
  - linux
  - osx
node_js:
  - node # latest node
  - 7.9.0 # vscode >= 1.16.0
  - 7.4.0 # vscode >= 1.12.0 < 1.16.0
  - 6.5.0 # vscode >= 1.8.0 < 1.12.0
git:
   submodules: false
matrix:
  allow_failures:
    - node_js: node
  fast_finish: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
script: npm run build
after_success:
  - codecov
jobs:
  include:
    - stage: wiki pages icons list update
      if: branch = master AND type != pull_request
      os: linux
      node_js: 7.9.0
      script: wpilgen
      after_success:
    - stage: docker vsi:latest
      if: branch = master AND type != pull_request
      sudo: required
      language: generic
      node_js:
      os:
      addons:
      cache:
      script:
        - ./docker/trigger-docker-vsi.sh $TRAVIS_TOKEN
      after_success:
    - stage: docker vsi:tag
      if: tag IS present
      sudo: required
      language: generic
      node_js:
      os:
      addons:
      cache:
      script:
        - ./docker/trigger-docker-vsi.sh --token $TRAVIS_TOKEN --tag $TRAVIS_TAG
      after_success:

# See this if we need to test the extension via vscode:
# https://code.visualstudio.com/Docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines
